server:
  port: 8060
spring:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BROKER}:${KAFKA_BROKER_PORT}
      key-serializer: ${KEY_SERIALIZER}  
      value-serializer: ${VALUE_SERIALIZER}
      properties:
        partitioner.class: ${PARTITIONER}
        lab.company: ${COMPANY_NAME}

kafka:
  topic-name: ${TOPIC_NAME}
  message-per-request: ${MESSAGE_PER_REQUEST}
  
logging:
  level:
    root: info