apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  ports:
  - port: 8060
    targetPort: 8060
    protocol: TCP
    name: http
  selector:
    app: kafka-producer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      hostAliases:
        - ip: "10.117.25.140"
          hostnames:
          - "kafka1"
          - "zookeeper1"
        - ip: "10.117.25.151"
          hostnames:
          - "kafka2"
          - "zookeeper2"
        - ip: "10.66.219.170"
          hostnames:
          - "kafka3"
          - "zookeeper3"
      containers:
      - name: producer
        image: nexweb1/kafka-producer:compress
        imagePullPolicy: Always
        ports:
        - containerPort: 8060
        env:
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: kafka-broker
        - name: KAFKA_BROKER_PORT
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: kafka-broker-port
        - name: KEY_SERIALIZER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: key-string-serializer
        - name: VALUE_SERIALIZER
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: value-string-serializer
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: kafka-topic-name
        - name: MESSAGE_PER_REQUEST
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: message-per-request
        - name: PARTITIONER
          valueFrom:
            configMapKeyRef:
              name: kafka-topic-config
              key: default-partitioner  # custom-partitioner
        - name: COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-topic-config
              key: company-name
        - name: COMPRESS_TYPE
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: compress